/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.HashMap;
import java.util.LinkedList;

public class SeMonsterGameTest {
  public void testAddPlayer(String player) {
    SeMonsterGame classUnderTest = new SeMonsterGame(App.createRandomList(10));
    classUnderTest.addPlayer("user");
    assertTrue(classUnderTest.playerMap.containsKey("user"));
  }

//   public void testDraw(String player){
//     SeMonsterGame classUnderTest = new SeMonsterGame(App.createRandomList(10));
//     assertEquals("user",classUnderTest.draw("user").toString());
//   }
}
